
[package]
name = "inspect-mo"
version = "0.1.0"
description = "Secure, type-safe validation and authorization for Motoko canisters."
repository = "https://github.com/icdevsorg/inspect-mo"
keywords = ["motoko","validation","authorization","inspect","guard"]
license = "MIT"

[dependencies]
core = "1.0.0"
ovs-fixed = "0.1.4"
class-plus = "0.0.1"
timer-tool = "0.1.1"
star = "0.1.1"
map = "9.0.1"
icrc10-mo = "0.0.1"
stable-local-log = "0.1.1"


[toolchain]
moc = "0.15.1"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"
